apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-catalogue-ingress
  namespace: product-catalogue-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: product-catalogue.local
      http:
        paths:
          - path: /v2(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-catalogue-svc
                port:
                  number: 80
